=== folio-org/mod-kb-ebsco-java/ramls/types/accessTypes/accessTypeCollectionItem.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Access Type object schema for a collection",
  "description": "Access Type object schema for a collection",
  "javaType": "org.folio.rest.jaxrs.model.AccessTypeCollectionItem",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "UUID of access type",
      "$ref": "../../raml-util/schemas/uuid.schema",
      "example": "f973c3b6-85fc-4d35-bda8-f31b568957bf"
    },
    "type": {
      "type": "string",
      "description": "Type of resource",
      "enum": ["accessTypes"],
      "example": "accessTypes"
    },
    "attributes": {
      "type": "object",
      "description": "Custom label object data attributes",
      "$ref": "accessTypeDataAttributes.json"
    },
    "creator": {
      "type": "object",
      "description": "User display info for creator of the note",
      "$ref": "userDisplayInfo.json",
      "readonly": true
    },
    "updater": {
      "type": "object",
      "description": "User display info for updater of the note",
      "$ref": "userDisplayInfo.json",
      "readonly": true
    },
    "metadata": {
      "type": "object",
      "description": "Metadata for the entity",
      "$ref": "../../raml-util/schemas/metadata.schema",
      "readonly": true
    }
  },
  "required": ["type", "attributes"]
}

=== folio-org/mod-kb-ebsco-java/ramls/examples/accessTypes/access_type_item_get_200_response.json
{
  "id": "3866efa9-4af8-4c4e-8fab-2451963cf0ea",
  "type": "accessTypes",
  "attributes": {
    "name": "Access Type 1",
    "description": "Access Type description 1"
  },
  "creator": {
    "lastName": "last name",
    "firstName": "first name"
  },
  "updater": {
    "lastName": "last name",
    "firstName": "first name"
  }
}
