=== folio-org/mod-kb-ebsco-java/ramls/types/packages/packageCollectionItem.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Package object schema for a collection",
  "description": "Package object schema for a collection",
  "javaType": "org.folio.rest.jaxrs.model.PackageCollectionItem",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier of package - combination of providerId-packageId",
      "example": "91525-1152699"
    },
    "type": {
      "type": "string",
      "description": "Type of resource",
      "example": "packages"
    },
    "attributes": {
      "type": "object",
      "description": "Package object data attributes",
      "$ref": "packageDataAttributes.json"
    },
    "relationships": {
      "type": "object",
      "description": "Displays if any resources are included in relationships",
      "$ref": "packageRelationships.json"
    }
  }
}

=== folio-org/mod-kb-ebsco-java/src/test/resources/responses/kb-ebsco/titles/expected-title-by-id-for-resource.json
{
  "id": "762169",
  "type": "titles",
  "attributes": {
    "name": "\"Great Satan\" Vs. the \"Mad Mullahs\": How the United States and Iran Demonize Each Other",
    "publisherName": "Praeger",
    "isTitleCustom": false,
    "subjects": [
      {
        "type": "BISAC",
        "subject": "SOCIAL SCIENCE / Ethnic Studies / General"
      }
    ],
    "identifiers": [
      {
        "id": "978-0-275-98214-0",
        "type": "ISBN",
        "subtype": "Print"
      },
      {
        "id": "978-1-282-40979-8",
        "type": "ISBN",
        "subtype": "Online"
      },
      {
        "id": "978-0-313-06800-3",
        "type": "ISBN",
        "subtype": "Online"
      }
    ],
    "publicationType": "Book",
    "isPeerReviewed": false,
    "contributors": [
      {
        "type": "author",
        "contributor": "Beeman, William O."
      }
    ]
  },
  "relationships": {
    "resources": {
      "meta": {
        "included": false
      }
    }
  }
}
